trigger: none 

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: python_script
    type: string
    default: 'Snowflake/employees-table.py'  # Default script name
    values:
      - Snowflake/employees-table.py
      - Snowflake/employees-table2.py

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Ensure Python 3.x is installed

- script: |
    python -m pip install --upgrade pip
    pip install snowflake-connector-python
  displayName: Install Python Dependencies

- script: |
    echo "Running the specified Python script: $(python_script)"
    python $(python_script)
  displayName: Run Python Script
