trigger:
- main  # Adjust to your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Ensure Python 3.x is installed

- script: |
    python -m pip install --upgrade pip
    pip install snowflake-connector-python
  displayName: Install Python Dependencies

- script: |
    python Snowflake/employees-table.py
  displayName: Run Snowflake Script
