trigger: none 

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: python_script
    type: string
    default: 'employees-table.py'  
    values:
      - employees-table.py
      - delete-employee.py

variables:
  DB_USERNAME: $(DB_USERNAME)
  DB_PASSWORD: $(DB_PASSWORD) 

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Ensure Python 3.x is installed

- script: |
    python -m pip install --upgrade pip
    pip install snowflake-connector-python
  displayName: Install Python Dependencies


- script: |
    echo "DB_USERNAME: $(DB_USERNAME)"
    echo "DB_PASSWORD: $(DB_PASSWORD)" 

- script: |
    echo "Running the specified Python script: ${{ parameters.python_script }}"
    python Snowflake/${{ parameters.python_script }}
  displayName: Run Python Script
  env:
    DB_USERNAME: $(DB_USERNAME)
    DB_PASSWORD: $(DB_PASSWORD)



